export enum ActivityEntityTypeEnum {
    Product = 1,
    Category = 2,
    Store = 3,
    Package = 4,
    Admin = 5,
    Offer = 6,
    Box = 7,
    Post = 8,
    LikeOnPost = 9,
    CommentOnPost = 10,
    ReplyOnComment = 11,
    Group = 12,
    Follow = 13,
    Follower = 14,
    SharePost = 15,
    SendGroupRequest = 16,
    AcceptGroupRequest = 17,
    ProfileImage = 18,
    NotificationSettings = 19,
    AccountSettings = 20,
    PrivacySettings = 21,
    ChangePassword = 22,
    AddInGroup = 23,
    LikeOnComment = 24,
    BlockUser = 25,
    ReportUser = 26,
    ReportPost = 27,
    CreateGroup = 28,
    ExternalShare=29

}